parserOptions:
  ecmaVersion: 2018
  sourceType: module
env:
  es6: true
  browser: true
  node: true
plugins:
  - react
  - react-hooks
extends:
  - prettier
  - prettier/react
  - eslint:recommended
  - plugin:react/recommended
rules:
  no-console: warn
  no-eval: error
  prettier/prettier: error
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  react/prop-types: off
  react/react-in-jsx-scope: off
settings:
  react:
    version: detect
